# Generated by Django 3.1.3 on 2020-12-01 22:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Breakfast', 'Breeeeakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=50),
        ),
    ]
