# Generated by Django 3.1.3 on 2020-11-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='blalaa', max_length=250),
        ),
    ]
