# Generated by Django 3.1.3 on 2020-12-02 16:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20201201_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=50),
        ),
    ]
