# Generated by Django 3.1.3 on 2020-11-28 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20201127_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='directions',
        ),
    ]
