# Generated by Django 3.1.3 on 2020-12-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipe', '0004_auto_20201202_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, through='recipe.RecipeIngredient', to='ingredients.Ingredient'),
        ),
    ]
