# Generated by Django 3.1.3 on 2020-12-15 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20201215_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='weight',
            field=models.PositiveSmallIntegerField(default=5, help_text='Add needed weight for the recipe', validators=[django.core.validators.MinValueValidator(2)], verbose_name='ingredient weight'),
        ),
    ]
