# Generated by Django 3.1.3 on 2020-11-29 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_favoriterecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={'ordering': ['user'], 'verbose_name': 'Favorite Recipe', 'verbose_name_plural': 'Favorite Recipes'},
        ),
    ]
