# Generated by Django 3.1.4 on 2020-12-16 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20201215_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='weight',
            field=models.IntegerField(default=10, help_text='Add needed weight for the recipe', validators=[django.core.validators.MinValueValidator(1)], verbose_name='ingredient weight'),
        ),
    ]
