# Generated by Django 3.1.4 on 2020-12-16 04:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20201215_2004'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='ingredient_weight_non_negative',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=10, help_text='Add needed weight for the recipe', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.9'))], verbose_name='ingredient weight'),
        ),
    ]
