# Generated by Django 3.1.3 on 2020-11-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['id'], 'verbose_name': 'Follow', 'verbose_name_plural': 'Followers'},
        ),
    ]
