name: foodgram

on:
  push:
    branches: [ master, developing ]
  pull_request:
    branches: [ master, developing ]
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt


      - name: Lint with flake8
        run: flake8 .

  connect_to_aws:

    needs: [ tests ]
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        - name: AWS Cli Processing
            run: |
              #!/bin/bash
              # Please add comma at the end of the RUNNERS strings
              # Don't add space after commas
              mkdir this_is_from_CI